# GRPC Server.
grpc:
  address: ":9090"
  name: "organize"
  logPath: "/tmp/log/"
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"
  etcdLink: ":9090"

# Global logging.
logger:
  level: "all"
  stdout: true
  logPath: "/tmp/log/"

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:123456@tcp(10.80.8.17:3807)/cqgf_product?loc=Local"
    debug: true

