// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/lj1570693659/gfcq_product/internal/logic/wechat"
)
