// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `json:"id"       description:"User ID"`
	Passport string      `json:"passport" description:"User Passport"`
	Password string      `json:"password" description:"User Password"`
	UserName string      `json:"userName" description:"User Nickname"`
	Nickname string      `json:"nickname" description:"User Nickname"`
	EmployeeId int32      `json:"employee_id" description:"User Nickname"`
	WorkNumber string      `json:"workNumber" description:"Work Number"`
	CreateTime *gtime.Time `json:"createTime" description:"Created Time"`
	UpdateTime *gtime.Time `json:"updateTime" description:"Updated Time"`
}
